DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    POWER TEXT NOT NULL
)
--create
INSERT INTO TB_HEROES (NAME, POWER)
VALUES
    ('Flash', 'Speed'),
    ('Aquaman', 'Fish'),
    ('Batman', 'Money')


--read
SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROEs WHERE NAME='Flash';

--update
UPDATE TB_HEROES
SET NAME= 'Goku', POWER= 'Deus'
WHERE ID = 1;

--delete
DELETE FROM TB_HEROES WHERE ID = 2;